export const ACTION_TYPES = {
  FETCH_USERS_PENDING: 'FETCH_USERS_PENDING',
  FETCH_USERS_RESOLVED: 'FETCH_USERS_RESOLVED',
  FETCH_USERS_REJECTED: 'FETCH_USERS_REJECTED',
  SET_SELECTED_PICTURE: 'SET_SELECTED_PICTURE',
};
